#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-external
    username: sosarx
    password: "$6$your_hashed_password_here"
  locale: en_US.UTF-8
  keyboard:
    layout: us
  ssh:
    install-server: true
    allow-pw: true
  storage:
    config:
      - type: disk
        id: disko
        match:
          size: 320GB
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        grub_device: true
        config:
          - type: partition
            size: 512M
            flag: boot
            filesystem: fat32
            mount: /boot/efi
          - type: partition
            size: 314G
            filesystem: ext4
            mount: /
          - type: partition
            size: 4G
            filesystem: swap
          - type: partition
            size: -1
            filesystem: ext4
            mount: /home
  packages:
    - vim
    - curl
    - net-tools
    - htop
    - openssh-server
  late-commands:
    - echo "Ubuntu installed on external drive" > /home/joe/install.log
    - sed -i 's/GRUB_TIMEOUT=10/GRUB_TIMEOUT=2/' /etc/default/grub
    - update-grub
